### ISSUE TITLE
SVP Commentez sur cet "issue" pour être ajouter comme collaborateur

### ISSUE THREAD

**Issue by koffisani** [koffisani/github-rep-for-iai#1]
Dans le but d'être ajouté comme contributeur (afin d'avoir accès en écriture), veuillez commenter ci-dessous. En indiquant votre nom et votre classe.

**Comment by scarlbry** [comment]
hello! C'est brigitte

**Comment by Cisseko** [comment]
Bonsoir, Je me nomme Moussa , étudiant en 2eme année Ingénieur à IAI Libreville

**Comment by mauricesewavi** [comment]
hello! that's good

**Comment by Maimounatou** [comment]
salut c'est maimounatou

**Comment by professeurlefluide7** [comment]
#bonjour je suis Jean Pierre ALLOGO O.
 je ne suis qu'un apprentis qui veux connaitre et échanger car j'ai des projets

**Comment by bangabonfils** [comment]
Bonsoir! C'est bangabonfils

**Comment by moupou** [comment]
bonsoir c'est moupou

**Comment by Ibrahimahadi** [comment]
bsoir monsieur

**Comment by bangabonfils** [comment]
```
                                                                                                                                                                                                                                                                                                                                                                                                                          Envoyé de mon smartphone BlackBerry 10.                                                                                                                                                                                                                De: IbrahimahadiEnvoyé: samedi 30 juillet 2016 19:19À: koffisani/github-rep-for-iaiRépondre à: koffisani/github-rep-for-iaiCc: bangabonfils; CommentObjet: Re: [koffisani/github-rep-for-iai] SVP Commentez sur cet "issue" pour être ajouter comme collaborateur (#1)bsoir monsieur
```

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by koffisani** [comment]
Merci à tous pour votre disponibilité. C'était un grand plaisir de vous voir disposés à apprendre.
**Merci beaucoup**

_@koffisani_

**Comment by Ibrahimahadi** [comment]
Merci

2016-07-31 0:46 GMT+02:00 Koffi Sani notifications@github.com:

**Comment by professeurlefluide7** [comment]
bonjour mr koffi. je me souviens de ce jour mais le comment utiliser ou
entrer dans la plate-forme m'ais redevenu inconnu.pouvez-vous m'aider à
nouveau je vous pris?
merci et veillez recevoir mes vœux de 2018 dont le plus important de mes
souhait est que Dieu soit votre partage premier et dernier.
très cordialement Jean Pierre ALLOGO OVONO

Le 31 juillet 2016 à 20:31, Ibrahimahadi <notifications@github.com> a écrit
:

**Comment by koffisani** [comment]
Bonjour @professeurlefluide7, bonne et heureuse année à toi aussi. J'espère que tout va bien là-bas. Essaie de m'écrire sur me@koffisani.ga et on pourra échanger des ressources pouvant t'aider.

Cordialement,
