### ISSUE TITLE
IAI_Connect

### ISSUE THREAD

**Issue by ngomtanouba** [koffisani/github-rep-for-iai#2]
Bonsoir je suis nouveau sur GitHub. Quelqu'un pourrait m'aider?

**Comment by koffisani** [comment]
Merci @BarthFox pour ta disponibilié. Merci énormément.

_@koffisani_

**Comment by ngomtanouba** [comment]
Merci @koffisani  c'est à moi de te remercier . Github me semble au premier contact très utile

**Comment by koffisani** [comment]
C'est très utile, @BarthFox. A toi de savoir l'utiliser. Explore les divers projets, empare-toi d'un, et travaille dessus.

**Comment by ngomtanouba** [comment]
Merci @koffisani je te tiendrai au informer de mon avancement
